name: Combined Workflow

on:
  workflow_dispatch:
  schedule:
    # Run every 5 minutes between 9:16 AM and 3:30 PM IST, Monday to Friday
    - cron: '46 3-10 * * 1-5'  # Runs at 9:16 AM to 3:30 PM IST (UTC+5:30)
    - cron: '51 3-10 * * 1-5'
    - cron: '56 3-10 * * 1-5'
    - cron: '01 4-11 * * 1-5'
    - cron: '06 4-11 * * 1-5'
    - cron: '11 4-11 * * 1-5'
    - cron: '16 4-11 * * 1-5'
    - cron: '21 4-11 * * 1-5'
    - cron: '26 4-11 * * 1-5'
    - cron: '31 4-11 * * 1-5'
    - cron: '36 4-11 * * 1-5'
    - cron: '41 4-11 * * 1-5'
    - cron: '46 4-11 * * 1-5'
    - cron: '51 4-11 * * 1-5'
    - cron: '56 4-11 * * 1-5'
    - cron: '01 5-12 * * 1-5'
    - cron: '06 5-12 * * 1-5'
    - cron: '11 5-12 * * 1-5'
    - cron: '16 5-12 * * 1-5'
    - cron: '21 5-12 * * 1-5'
    - cron: '26 5-12 * * 1-5'
    - cron: '31 5-12 * * 1-5'
    - cron: '36 5-12 * * 1-5'
    - cron: '41 5-12 * * 1-5'
    - cron: '46 5-12 * * 1-5'
    - cron: '51 5-12 * * 1-5'
    - cron: '56 5-12 * * 1-5'
    - cron: '01 6-13 * * 1-5'
    - cron: '06 6-13 * * 1-5'
    - cron: '11 6-13 * * 1-5'
    - cron: '16 6-13 * * 1-5'
    - cron: '21 6-13 * * 1-5'
    - cron: '26 6-13 * * 1-5'
    - cron: '31 6-13 * * 1-5'
    - cron: '36 6-13 * * 1-5'
    - cron: '41 6-13 * * 1-5'
    - cron: '46 6-13 * * 1-5'
    - cron: '51 6-13 * * 1-5'
    - cron: '56 6-13 * * 1-5'
    - cron: '01 7-14 * * 1-5'
    - cron: '06 7-14 * * 1-5'
    - cron: '11 7-14 * * 1-5'
    - cron: '16 7-14 * * 1-5'
    - cron: '21 7-14 * * 1-5'
    - cron: '26 7-14 * * 1-5'
    - cron: '31 7-14 * * 1-5'
    - cron: '36 7-14 * * 1-5'
    - cron: '41 7-14 * * 1-5'
    - cron: '46 7-14 * * 1-5'
    - cron: '51 7-14 * * 1-5'
    - cron: '56 7-14 * * 1-5'
    - cron: '01 8-15 * * 1-5'
    - cron: '06 8-15 * * 1-5'
    - cron: '11 8-15 * * 1-5'
    - cron: '16 8-15 * * 1-5'
    - cron: '21 8-15 * * 1-5'
    - cron: '26 8-15 * * 1-5'
    - cron: '31 8-15 * * 1-5'
    - cron: '36 8-15 * * 1-5'
    - cron: '41 8-15 * * 1-5'
    - cron: '46 8-15 * * 1-5'
    - cron: '51 8-15 * * 1-5'
    - cron: '56 8-15 * * 1-5'
    - cron: '01 9-16 * * 1-5'
    - cron: '06 9-16 * * 1-5'
    - cron: '11 9-16 * * 1-5'
    - cron: '16 9-16 * * 1-5'
    - cron: '21 9-16 * * 1-5'
    - cron: '26 9-16 * * 1-5'
    - cron: '31 9-16 * * 1-5'
    - cron: '36 9-16 * * 1-5'
    - cron: '41 9-16 * * 1-5'

jobs:
  download_and_store_csv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance==0.2.30
          pip install pandas

      - name: Download Nifty50 Data
        run: |
          python3 scripts/download_nifty50_data.py

      - name: Store CSV data to SQLite DB
        run: |
          python3 scripts/store_csv_to_db.py

      - name: Commit and push updated files
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add temp_csv/*.csv nifty50_data_v1.db
          git commit -m "Download Nifty50 data, store to DB, and update CSVs" || exit 0
          git pull origin main --rebase || git rebase --abort
          git merge --strategy-option ours origin/main || git merge --abort
          git push https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/chiragpalan/stock_predictions_rnn_v3.git HEAD:main

  predict_rnn:
    runs-on: ubuntu-latest
    needs: download_and_store_csv
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run predict_rnn.py
        run: |
          python predict_rnn.py

      - name: Check if predictions.db exists
        run: |
          if [ -f "predictions/predictions.db" ]; then
            echo "Prediction database found."
            git config --global user.name "GitHub Actions"
            git config --global user.email "github-actions@github.com"
            git pull origin main || git merge --strategy-option ours origin/main
            git add predictions/predictions.db
            git commit -m "Update prediction database"
            git push https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/chiragpalan/stock_predictions_rnn_v3.git HEAD:main
          else
            echo "No predictions.db file found, skipping commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
