name: Run Predictions

on:
  workflow_dispatch:

jobs:
  run-predictions:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy tensorflow scikit-learn

    - name: Run prediction script
      run: |
        mkdir -p predictions
        python predict_rnn.py

    - name: Check for .db files in predictions directory
      id: check-predictions
      run: |
        if ls predictions/*.db 1> /dev/null 2>&1; then
          echo "::set-output name=has_db_files::true"
        else
          echo "::set-output name=has_db_files::false"
        fi

    - name: Commit and push changes
      if: success() && steps.check-predictions.outputs.has_db_files == 'true'
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add predictions/*.db
        git commit -m 'Update predictions database'
        git pull --rebase
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
